### ISSUE TITLE
更改`sync-request`模块

### ISSUE THREAD

**Issue by earthjasonlin** [HuanLinOTO/GenshinCloudGameHelper#6]
今天想捣腾的时候突然发现遇到如下报错：
```
J:\Projects\GenshinCloudGameHelper\node_modules\sync-rpc\lib\index.js:146
      throw new Error(
      ^

Error: nodeNC failed:

node:events:490
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'

Node.js v19.6.0

    at sendMessage (J:\Projects\GenshinCloudGameHelper\node_modules\sync-rpc\lib\index.js:146:13)
    at createClient (J:\Projects\GenshinCloudGameHelper\node_modules\sync-rpc\lib\index.js:173:27)
    at Object.<anonymous> (J:\Projects\GenshinCloudGameHelper\node_modules\sync-request\lib\index.js:16:14)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (J:\Projects\GenshinCloudGameHelper\index.js:1:17)

Node.js v19.6.0
```
查了一下他们的[官方github仓库](https://github.com/ForbesLindesay/sync-request)发现挺多人遇到这个问题的，README里面也说最好不要用这个模块来生产环境，所以或许可以换一个模块来做http请求

**Comment by earthjasonlin** [comment]
好吧，发现是我的抓包软件造成的。。。

**Comment by HuanLinOTO** [comment]
说实话这个项目我想丢了，刚学 node 的时候写的，纯纯屎山（（

我找个时间换 axios

**Comment by earthjasonlin** [comment]
别啊，功能好用

**Comment by HuanLinOTO** [comment]
https://github.com/HuanLinOTO/GenshinCloudPlayHelper/tree/refactor

尝试一下，我手上没号测试，没有功能性更改

**Comment by earthjasonlin** [comment]
草，我刚用sync-request给自动ackNotifications搞出来了

**Comment by HuanLinOTO** [comment]
> 草，我刚用sync-request给自动ackNotifications搞出来了

没事的，没有功能性更改，只要能跑一遍没报错就是没问题

**Comment by earthjasonlin** [comment]
```
PS D:\Downloads\GenshinCloudPlayHelper-refactor> node src/index
[I] GenshinCloudPlayHelper 获取成功
[I] GenshinCloudPlayHelper 检测到6个配置文件：
[I] GenshinCloudPlayHelper 1.json
[I] GenshinCloudPlayHelper 正在检测配置有效性
[I] GenshinCloudPlayHelper 检测完毕！
D:\Downloads\GenshinCloudPlayHelper-refactor\src\index.js:45
(async () => {
^

TypeError: log.info(...) is not a function
    at Object.<anonymous> (D:\Downloads\GenshinCloudPlayHelper-refactor\src\index.js:45:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.5.1
```

**Comment by HuanLinOTO** [comment]
L13
```js
global.log = {
```

改为

```js
const log = {
```

**Comment by earthjasonlin** [comment]
```
PS D:\Downloads\GenshinCloudPlayHelper> node src/index
[I] GenshinCloudPlayHelper 开始获取全局配置
[I] GenshinCloudPlayHelper 获取成功
D:\Downloads\GenshinCloudPlayHelper\src\config.js:73
    log.info(`检测到${configsList.length}个配置文件：`)
    ^

ReferenceError: log is not defined
    at exports.getConfigs (D:\Downloads\GenshinCloudPlayHelper\src\config.js:73:5)       
    at Object.<anonymous> (D:\Downloads\GenshinCloudPlayHelper\src\index.js:39:15)       
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.5.1
```

**Comment by earthjasonlin** [comment]
```
PS D:\Downloads\GenshinCloudPlayHelper> node src/index
[I] GenshinCloudPlayHelper 开始获取全局配置
[I] GenshinCloudPlayHelper 获取成功
D:\Downloads\GenshinCloudPlayHelper\src\config.js:73
    log.info(`检测到${configsList.length}个配置文件：`)
    ^

ReferenceError: log is not defined
    at exports.getConfigs (D:\Downloads\GenshinCloudPlayHelper\src\config.js:73:5)
    at Object.<anonymous> (D:\Downloads\GenshinCloudPlayHelper\src\index.js:39:15)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.5.1
```

**Comment by HuanLinOTO** [comment]
拉取最新 commit 后尝试

**Comment by earthjasonlin** [comment]
```
PS D:\Downloads\GenshinCloudPlayHelper> node src/index
D:\Downloads\GenshinCloudPlayHelper\src\logger.js:1
const baseLogger = new reggol("GenshinCloudPlayHelper")
                   ^

ReferenceError: reggol is not defined
    at Object.<anonymous> (D:\Downloads\GenshinCloudPlayHelper\src\logger.js:1:20)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (D:\Downloads\GenshinCloudPlayHelper\src\config.js:5:17)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)

Node.js v20.5.1
```

**Comment by HuanLinOTO** [comment]
拉取最新代码再试试...

拿着备忘录疯狂改代码.jpg

**Comment by earthjasonlin** [comment]
```
PS D:\Downloads\GenshinCloudPlayHelper> node src/index
D:\Downloads\GenshinCloudPlayHelper\src\index.js:9
(async () => {
^

TypeError: require(...) is not a function
    at Object.<anonymous> (D:\Downloads\GenshinCloudPlayHelper\src\index.js:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.5.1
```
啊？不是word吗（doge刁花.gif）要不加个联系方式吧。

**Comment by HuanLinOTO** [comment]
> ```
> PS D:\Downloads\GenshinCloudPlayHelper> node src/index
> D:\Downloads\GenshinCloudPlayHelper\src\index.js:9
> (async () => {
> ^
> 
> TypeError: require(...) is not a function
>     at Object.<anonymous> (D:\Downloads\GenshinCloudPlayHelper\src\index.js:9:1)
>     at Module._compile (node:internal/modules/cjs/loader:1233:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
>     at Module.load (node:internal/modules/cjs/loader:1091:32)
>     at Module._load (node:internal/modules/cjs/loader:938:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
>     at node:internal/main/run_main_module:23:47
> 
> Node.js v20.5.1
> ```
> 
> 啊？不是word吗（doge刁花.gif）要不加个联系方式吧。

3509949348

我要把自己笨死了

**Comment by earthjasonlin** [comment]
加了

**Comment by HuanLinOTO** [comment]
没收到 qq 哦

**Comment by earthjasonlin** [comment]
。。。tim又抽风了
